[tool.poetry]
name = "karagen"
version = "0.1.0"
description = ""
authors = ["Beinan Li <li.beinan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
kkpyutil = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
